export const sroutes = [
    { label: 'Page 1', path: 'page1', component: Page1},
    { label: 'Language', path: 'languageselector', component: LanguageSelector},
    { label: 'Survey Consent', path: 'surveyconsent', component: SurveyConsent},
    { label: 'Greetings', path: 'greetings', component: Greetings},
    { label: 'Residence 1', path: 'residence1', component: Residence1},
    { label: 'Main Purpose', path: 'mainpurpose', component: MainPurpose},
    { label: 'Visit Frequency Form', path: 'visitfrequencyform', component: VisitFrequencyForm},
    { label: 'Form', path: 'form', component: Form},
    { label: 'Branching Select', path: 'branchingselect', component: BranchingSelect},
    { label: 'Survey Evaluation VERSION1', path: 'surveyevaluation05', component: SurveyEvaluation05},
    // { label: 'Survey Evaluation VERSION2', path: 'surveyevaluationb', component: },
    { label: 'Thank You Message', path: 'thankyoumessage', component: ThankYouMessage},
    { label: 'Will Recommend', path: 'willrecom', component: Willrecom},
    { label: 'Where Learn', path: 'wherelearn', component: WhereLearn},
    { label: 'Survey Venue', path: 'surveyvenue', component: SurveyVenue},
    { label: 'Open Ended Lifestyle', path: 'openended2', component: OpenEnded2},
    { label: 'Open Ended 1', path: 'openended1', component: OpenEndedHotel},
    // { label: '(DUPLICATE)How Many Visits', path: 'howmanyvisits', component: },
    { label: 'Primary Attraction', path: 'primaryatt', component: PrimaryAtt},
    { label: 'Rate Attraction', path: 'rateattraction', component: RateAttraction},
    { label: 'Events Open 1', path: 'eventsopen1', component: EventsOpen1},
    { label: 'Attractions Feedback', path: 'attractionsfeedback', component: AttractionsFeedback},
    { label: 'Package Tour Feedback', path: 'packagetourfeedback', component: PackageTourFeedback},
    { label: 'Attraction Form', path: 'attractionform', component: AttractionForm},
    { label: 'Services 2', path: 'services2', component: Services2},
    { label: 'Services 1', path: 'services1', component: Services1},
    { label: 'Destination Shopping List', path: 'destinationshoppinglist', component: DestinationShoppingList},
    { label: 'Visit Counter', path: 'visitcounteratt', component: VisitCounterAtt},
    { label: 'Travel Question', path: 'travelquestion', component: TravelQuestion},
    { label: 'Travel With', path: 'travelwith', component: TravelWith},
    { label: 'Travel Options', path: 'traveloptions', component: TravelOptions},
    { label: 'Package Tour Items', path: 'packagetouritems', component: PackageTourItems},
    { label: 'Package Paid', path: 'packagepaid', component: PackagePaid},
    { label: 'Expense Tracker', path: 'expensetracker', component: ExpenseTracker},
    { label: 'Percentage Share List', path: 'percentagesharelist', component: PercentageShareList},
    // { label: '(DUPLICATE)Expense Companions', path: 'expensecompanions', component: },
    { label: 'Pack Transpo', path: 'packtranspo', component: PackTranspo},
    { label: 'How Many Nights', path: 'howmanynights', component: HowManyNights},
    { label: 'Accommodation Form', path: 'accommodationform', component: AccommodationForm},
    { label: 'Booking Form', path: 'bookingform', component: BookingForm},
    { label: 'Where Stay Arrival', path: 'wherestayarrival', component: WhereStayArrival},
    // { label: '(IGNORE)Where Stay Departure', path: 'wherestaydepart', component: },
    { label: 'Accommodation Open 1', path: 'accomodationopen1', component: AccomodationOpen1},
    { label: 'Accommodation Open 2', path: 'accomodationopen2', component: AccomodationOpen2},
    { label: 'Transportation 3', path: 'transportation3', component: Transportation3},
    { label: 'Transportation 1', path: 'transportation1', component: Transportation1},
    { label: 'Transportation 2', path: 'transportation2', component: Transportation2},
    { label: 'Personal Profile 2', path: 'pprofile2', component: PProfile2},
    { label: 'Personal Profile 1', path: 'pprofile1', component: PProfile1},
    { label: 'Proponent LGU', path: 'proponentlgu', component: ProponentLgu},

];
