export const  dummyData = {
    totalSurveysCompleted: 4789,
    surveyCompletionRate: 75, // Percentage
    averageTimeToComplete: '5m 30s',
    dropOffRate: 25, // Percentage
    responseRate: 60, // Percentage
    surveySatisfactionScore: 4.2, // Out of 5
    surveyDistribution: {
        TPMS: 50,
        Establishment: 20,
        Attraction: 52,
        Transportation: 22,
        Barangay: 23
    },
    surveyResponsesByDevice: {
        desktop: 60,
        mobile: 50,
        tablet: 10,
    },
    surveyResponsesByRegion: {
        Korean: 70,
        Chinese: 30,
        Filipino: 15,
        Japanese: 5,
    },
    surveyResponsesByAgeGroup: {
        '18-24': 20,
        '25-34': 50,
        '35-44': 30,
        '45-54': 15,
        '55+': 5,
    },
    surveyResponsesByGender: {
        male: 60,
        female: 55,
        other: 5,
    },
    surveyResponsesByIncomeLevel: {
        low: 20,
        medium: 70,
        high: 30,
    },
    surveyResponsesByEducationLevel: {
        highSchool: 15,
        bachelor: 50,
        master: 30,
        doctorate: 5,
    },
    surveyResponsesByEmploymentStatus: {
        employed: 80,
        unemployed: 10,
        student: 10,
    },
    surveyResponsesByIndustry: {
        technology: 30,
        healthcare: 20,
        finance: 15,
        education: 10,
        retail: 10,
        other: 15,
    },
    surveyResponsesByCompanySize: {
        small: 20,
        medium: 50,
        large: 30,
    },
    surveyResponsesByJobRole: {
        manager: 30,
        developer: 20,
        designer: 10,
        analyst: 15,
        other: 25,
    },
    surveyResponsesByTenure: {
        '0-1 years': 20,
        '1-3 years': 30,
        '3-5 years': 25,
        '5+ years': 25,
    },
    surveyResponsesByFrequency: {
        daily: 10,
        weekly: 20,
        monthly: 50,
        quarterly: 15,
        yearly: 5,
    },
    surveyResponsesByChannel: {
        email: 60,
        sms: 20,
        inApp: 20,
    },
    surveyResponsesByTimeOfDay: {
        morning: 30,
        afternoon: 40,
        evening: 20,
        night: 10,
    },
    surveyResponsesByDayOfWeek: {
        monday: 20,
        tuesday: 25,
        wednesday: 20,
        thursday: 15,
        friday: 10,
        saturday: 5,
        sunday: 5,
    },
    surveyResponsesByMonth: {
        january: 10,
        february: 15,
        march: 20,
        april: 15,
        may: 10,
        june: 5,
        july: 5,
        august: 5,
        september: 5,
        october: 5,
        november: 5,
        december: 5,
    },
    surveyResponsesByYear: {
        2020: 10,
        2021: 20,
        2022: 30,
        2023: 40,
    },
    surveyResponsesByCustomerType: {
        new: 30,
        returning: 70,
    },
    surveyResponsesByCustomerLoyalty: {
        low: 20,
        medium: 50,
        high: 30,
    },
    surveyResponsesByCustomerSatisfaction: {
        low: 10,
        medium: 30,
        high: 60,
    },
    surveyResponsesByCustomerEngagement: {
        low: 20,
        medium: 50,
        high: 30,
    },
    surveyResponsesByCustomerRetention: {
        low: 10,
        medium: 30,
        high: 60,
    },
    surveyResponsesByCustomerChurn: {
        low: 20,
        medium: 50,
        high: 30,
    },
    surveyResponsesByCustomerLifetimeValue: {
        low: 10,
        medium: 30,
        high: 60,
    },
    surveyResponsesByCustomerReferral: {
        low: 20,
        medium: 50,
        high: 30,
    },
    surveyResponsesByCustomerFeedback: {
        positive: 70,
        neutral: 20,
        negative: 10,
    },
    surveyResponsesByCustomerSupport: {
        low: 10,
        medium: 30,
        high: 60,
    },
    surveyResponsesByCustomerExperience: {
        low: 10,
        medium: 30,
        high: 60,
    },
    surveyResponsesByCustomerJourney: {
        awareness: 20,
        consideration: 30,
        decision: 25,
        retention: 15,
        advocacy: 10,
    },
    surveyResponsesByCustomerTouchpoints: {
        website: 30,
        socialMedia: 20,
        phone: 10,
        inPerson: 10,
        other: 10,
    },
    surveyResponsesByCustomerSegmentation: {
        demographic: 30,
        geographic: 20,
        psychographic: 20,
        behavioral: 30,
    },
    surveyResponsesByCustomerPersona: {
        persona1: 20,
        persona2: 30,
        persona3: 25,
        persona4: 15,
        persona5: 10,
    },
    surveyResponsesByCustomerNeeds: {
        need1: 20,
        need2: 30,
        need3: 25,
        need4: 15,
        need5: 10,
    },
    surveyResponsesByCustomerPainPoints: {
        painPoint1: 20,
        painPoint2: 30,
        painPoint3: 25,
        painPoint4: 15,
        painPoint5: 10,
    },
    surveyResponsesByCustomerGoals: {
        goal1: 20,
        goal2: 30,
        goal3: 25,
        goal4: 15,
        goal5: 10,
    },
    surveyResponsesByCustomerMotivations: {
        motivation1: 20,
        motivation2: 30,
        motivation3: 25,
        motivation4: 15,
        motivation5: 10,
    },
    surveyResponsesByCustomerBarriers: {
        barrier1: 20,
        barrier2: 30,
        barrier3: 25,
        barrier4: 15,
        barrier5: 10,
    },
    surveyResponsesByCustomerPreferences: {
        preference1: 20,
        preference2: 30,
        preference3: 25,
        preference4: 15,
        preference5: 10,
    },
    surveyResponsesByCustomerExpectations: {
        expectation1: 20,
        expectation2: 30,
        expectation3: 25,
        expectation4: 15,
        expectation5: 10,
    },
    surveyResponsesByCustomerSatisfactionDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerLoyaltyDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerEngagementDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerRetentionDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerChurnDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerLifetimeValueDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerReferralDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerFeedbackDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerSupportDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerExperienceDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerJourneyDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerTouchpointsDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerSegmentationDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerPersonaDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerNeedsDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerPainPointsDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerGoalsDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerMotivationsDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerBarriersDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerPreferencesDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
    surveyResponsesByCustomerExpectationsDrivers: {
        driver1: 20,
        driver2: 30,
        driver3: 25,
        driver4: 15,
        driver5: 10,
    },
};
