export const MAINPURPOSE = "mainpurpose"
export const VISITFREQUENCYFORM = "VisitFrequencyForm"
export const RESIDENCE1 = "residence1"
export const SURVEYCONSENT = "SurveyConsent"
export const FORM = "Form"
export const GREETINGS = "Greetings"
export const BRANCHINGSELECT = "BranchingSelect"